/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthId = Principal;
export interface AvailabilitySlot {
  'id' : bigint,
  'status' : SlotStatus,
  'date' : string,
  'createdAt' : Timestamp,
  'time' : [] | [string],
  'providerId' : bigint,
}
export interface AvailabilitySlotInput {
  'status' : SlotStatus,
  'date' : string,
  'time' : [] | [string],
}
export interface Booking {
  'id' : bigint,
  'customerNote' : [] | [string],
  'status' : BookingStatus,
  'scheduledDate' : string,
  'scheduledTime' : [] | [string],
  'listingId' : bigint,
  'createdAt' : Timestamp,
  'jobDetails' : string,
  'updatedAt' : Timestamp,
  'address' : string,
  'category' : ServiceCategory,
  'customerId' : UserId,
  'providerId' : bigint,
}
export interface BookingInput {
  'customerNote' : [] | [string],
  'scheduledDate' : string,
  'scheduledTime' : [] | [string],
  'listingId' : bigint,
  'jobDetails' : string,
  'address' : string,
}
export type BookingStatus = { 'scheduled' : null } |
  { 'requested' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'reviewed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface IdentityAttributes {
  'principal' : AuthId,
  'lastSeenAt' : bigint,
  'displayName' : [] | [string],
  'source' : IdentitySource,
  'firstSeenAt' : bigint,
  'email' : [] | [string],
}
export type IdentitySource = { 'internetIdentity' : null } |
  { 'google' : null } |
  { 'email' : null };
export type MarketplaceRole = { 'admin' : null } |
  { 'provider' : null } |
  { 'customer' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'bookingId' : bigint,
  'read' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
}
export interface MessageInput { 'content' : string, 'bookingId' : bigint }
export interface Provider {
  'id' : bigint,
  'ratingSum' : bigint,
  'verificationNote' : [] | [string],
  'ratingCount' : bigint,
  'ownerPrincipal' : UserId,
  'logo' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'serviceCategories' : Array<ServiceCategory>,
  'description' : [] | [string],
  'updatedAt' : Timestamp,
  'companyName' : string,
  'serviceAreas' : Array<string>,
  'verificationStatus' : VerificationStatus,
}
export interface ProviderInput {
  'logo' : [] | [ExternalBlob],
  'serviceCategories' : Array<ServiceCategory>,
  'description' : [] | [string],
  'companyName' : string,
  'serviceAreas' : Array<string>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Review {
  'id' : bigint,
  'bookingId' : bigint,
  'createdAt' : Timestamp,
  'hidden' : boolean,
  'updatedAt' : Timestamp,
  'providerResponse' : [] | [string],
  'customerId' : UserId,
  'rating' : bigint,
  'writtenText' : string,
  'providerId' : bigint,
}
export interface ReviewInput {
  'bookingId' : bigint,
  'rating' : bigint,
  'writtenText' : string,
}
export interface SearchFilters {
  'serviceArea' : [] | [string],
  'minRating' : [] | [bigint],
  'category' : [] | [ServiceCategory],
  'keyword' : [] | [string],
  'maxPriceCents' : [] | [bigint],
  'availableOn' : [] | [string],
}
export interface SearchResult {
  'listing' : ServiceListing,
  'provider' : Provider,
}
export type ServiceCategory = { 'boxTruck' : null } |
  { 'relocation' : null } |
  { 'moving' : null } |
  { 'trashHaul' : null };
export interface ServiceListing {
  'id' : bigint,
  'serviceArea' : string,
  'title' : string,
  'active' : boolean,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'category' : ServiceCategory,
  'priceUnit' : string,
  'priceCents' : bigint,
  'providerId' : bigint,
  'photos' : Array<ExternalBlob>,
}
export interface ServiceListingInput {
  'serviceArea' : string,
  'title' : string,
  'active' : boolean,
  'description' : string,
  'category' : ServiceCategory,
  'priceUnit' : string,
  'priceCents' : bigint,
  'photos' : Array<ExternalBlob>,
}
export type SlotStatus = { 'blocked' : null } |
  { 'available' : null };
export type Timestamp = bigint;
export interface User {
  'principal' : UserId,
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : MarketplaceRole,
  'email' : [] | [string],
  'updatedAt' : Timestamp,
  'phone' : [] | [string],
  'avatar' : [] | [ExternalBlob],
}
export type UserId = Principal;
export interface UserInput {
  'displayName' : string,
  'role' : MarketplaceRole,
  'email' : [] | [string],
  'phone' : [] | [string],
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__bookings' : ActorMethod<[], any>,
  '__identities' : ActorMethod<[], any>,
  '__listings' : ActorMethod<[], any>,
  '__messages' : ActorMethod<[], any>,
  '__nextBookingId' : ActorMethod<[], any>,
  '__nextListingId' : ActorMethod<[], any>,
  '__nextMessageId' : ActorMethod<[], any>,
  '__nextProviderId' : ActorMethod<[], any>,
  '__nextReviewId' : ActorMethod<[], any>,
  '__nextSlotId' : ActorMethod<[], any>,
  '__openAIApiKey' : ActorMethod<[], any>,
  '__providers' : ActorMethod<[], any>,
  '__reviews' : ActorMethod<[], any>,
  '__slots' : ActorMethod<[], any>,
  '__users' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'acceptBooking' : ActorMethod<[bigint], Booking>,
  'approveProvider' : ActorMethod<[bigint], Provider>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockAvailabilitySlot' : ActorMethod<[bigint], AvailabilitySlot>,
  'cancelBooking' : ActorMethod<[bigint], Booking>,
  'checkAvailability' : ActorMethod<[bigint, string, [] | [string]], boolean>,
  'completeBooking' : ActorMethod<[bigint], Booking>,
  'createBooking' : ActorMethod<[BookingInput], Booking>,
  'createListing' : ActorMethod<[ServiceListingInput], ServiceListing>,
  'createReview' : ActorMethod<[ReviewInput], Review>,
  'declineBooking' : ActorMethod<[bigint], Booking>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'generateListingDescription' : ActorMethod<[string], string>,
  'generatePromotionalContent' : ActorMethod<[string], string>,
  'generateTitleAndTagline' : ActorMethod<[string], Array<string>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], [] | [ServiceListing]>,
  'getMyBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getMyDisplayName' : ActorMethod<[], [] | [string]>,
  'getMyEmail' : ActorMethod<[], [] | [string]>,
  'getMyIdentity' : ActorMethod<[], [] | [IdentityAttributes]>,
  'getMyIdentitySource' : ActorMethod<[], [] | [IdentitySource]>,
  'getMyProvider' : ActorMethod<[], [] | [Provider]>,
  'getMyUser' : ActorMethod<[], [] | [User]>,
  'getProvider' : ActorMethod<[bigint], [] | [Provider]>,
  'getReview' : ActorMethod<[bigint], [] | [Review]>,
  'getThread' : ActorMethod<[bigint], Array<Message>>,
  'getUnreadMessageCount' : ActorMethod<[bigint], bigint>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'listAvailabilitySlots' : ActorMethod<[bigint], Array<AvailabilitySlot>>,
  'listListingsByCategory' : ActorMethod<
    [ServiceCategory],
    Array<ServiceListing>
  >,
  'listListingsByProvider' : ActorMethod<[bigint], Array<ServiceListing>>,
  'listMyBookings' : ActorMethod<[], Array<Booking>>,
  'listProviderBookings' : ActorMethod<[bigint], Array<Booking>>,
  'listProviders' : ActorMethod<[], Array<Provider>>,
  'listProvidersByCategory' : ActorMethod<[ServiceCategory], Array<Provider>>,
  'listReviewsByBooking' : ActorMethod<[bigint], Array<Review>>,
  'listReviewsByProvider' : ActorMethod<[bigint], Array<Review>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'markThreadRead' : ActorMethod<[bigint], undefined>,
  'moderateReview' : ActorMethod<
    [bigint, { 'hide' : null } | { 'restore' : null }],
    Review
  >,
  'registerProvider' : ActorMethod<[ProviderInput], Provider>,
  'reinstateProvider' : ActorMethod<[bigint], Provider>,
  'rejectProvider' : ActorMethod<[bigint, string], Provider>,
  'respondToReview' : ActorMethod<[bigint, string], Review>,
  'scheduleBooking' : ActorMethod<[bigint], Booking>,
  'schema' : ActorMethod<[], string>,
  'searchProviders' : ActorMethod<[SearchFilters], Array<SearchResult>>,
  'sendMessage' : ActorMethod<[MessageInput], Message>,
  'setAvailabilitySlot' : ActorMethod<
    [AvailabilitySlotInput],
    AvailabilitySlot
  >,
  'setOpenAIApiKey' : ActorMethod<[string], undefined>,
  'startBooking' : ActorMethod<[bigint], Booking>,
  'suspendProvider' : ActorMethod<[bigint, string], Provider>,
  'updateListing' : ActorMethod<[bigint, ServiceListingInput], ServiceListing>,
  'updateMyProvider' : ActorMethod<[ProviderInput], Provider>,
  'upsertMyUser' : ActorMethod<[UserInput], User>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];