/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const BookingStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'reviewed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ServiceCategory = IDL.Variant({
  'boxTruck' : IDL.Null,
  'relocation' : IDL.Null,
  'moving' : IDL.Null,
  'trashHaul' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerNote' : IDL.Opt(IDL.Text),
  'status' : BookingStatus,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Opt(IDL.Text),
  'listingId' : IDL.Nat,
  'createdAt' : Timestamp,
  'jobDetails' : IDL.Text,
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
  'category' : ServiceCategory,
  'customerId' : UserId,
  'providerId' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Provider = IDL.Record({
  'id' : IDL.Nat,
  'ratingSum' : IDL.Nat,
  'verificationNote' : IDL.Opt(IDL.Text),
  'ratingCount' : IDL.Nat,
  'ownerPrincipal' : UserId,
  'logo' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'serviceCategories' : IDL.Vec(ServiceCategory),
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'companyName' : IDL.Text,
  'serviceAreas' : IDL.Vec(IDL.Text),
  'verificationStatus' : VerificationStatus,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SlotStatus = IDL.Variant({
  'blocked' : IDL.Null,
  'available' : IDL.Null,
});
export const AvailabilitySlot = IDL.Record({
  'id' : IDL.Nat,
  'status' : SlotStatus,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'time' : IDL.Opt(IDL.Text),
  'providerId' : IDL.Nat,
});
export const BookingInput = IDL.Record({
  'customerNote' : IDL.Opt(IDL.Text),
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Opt(IDL.Text),
  'listingId' : IDL.Nat,
  'jobDetails' : IDL.Text,
  'address' : IDL.Text,
});
export const ServiceListingInput = IDL.Record({
  'serviceArea' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'priceUnit' : IDL.Text,
  'priceCents' : IDL.Nat,
  'photos' : IDL.Vec(ExternalBlob),
});
export const ServiceListing = IDL.Record({
  'id' : IDL.Nat,
  'serviceArea' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'category' : ServiceCategory,
  'priceUnit' : IDL.Text,
  'priceCents' : IDL.Nat,
  'providerId' : IDL.Nat,
  'photos' : IDL.Vec(ExternalBlob),
});
export const ReviewInput = IDL.Record({
  'bookingId' : IDL.Nat,
  'rating' : IDL.Nat,
  'writtenText' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'createdAt' : Timestamp,
  'hidden' : IDL.Bool,
  'updatedAt' : Timestamp,
  'providerResponse' : IDL.Opt(IDL.Text),
  'customerId' : UserId,
  'rating' : IDL.Nat,
  'writtenText' : IDL.Text,
  'providerId' : IDL.Nat,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AuthId = IDL.Principal;
export const IdentitySource = IDL.Variant({
  'internetIdentity' : IDL.Null,
  'google' : IDL.Null,
  'email' : IDL.Null,
});
export const IdentityAttributes = IDL.Record({
  'principal' : AuthId,
  'lastSeenAt' : IDL.Nat,
  'displayName' : IDL.Opt(IDL.Text),
  'source' : IdentitySource,
  'firstSeenAt' : IDL.Nat,
  'email' : IDL.Opt(IDL.Text),
});
export const MarketplaceRole = IDL.Variant({
  'admin' : IDL.Null,
  'provider' : IDL.Null,
  'customer' : IDL.Null,
});
export const User = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : MarketplaceRole,
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'phone' : IDL.Opt(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'bookingId' : IDL.Nat,
  'read' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
});
export const ProviderInput = IDL.Record({
  'logo' : IDL.Opt(ExternalBlob),
  'serviceCategories' : IDL.Vec(ServiceCategory),
  'description' : IDL.Opt(IDL.Text),
  'companyName' : IDL.Text,
  'serviceAreas' : IDL.Vec(IDL.Text),
});
export const SearchFilters = IDL.Record({
  'serviceArea' : IDL.Opt(IDL.Text),
  'minRating' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(ServiceCategory),
  'keyword' : IDL.Opt(IDL.Text),
  'maxPriceCents' : IDL.Opt(IDL.Nat),
  'availableOn' : IDL.Opt(IDL.Text),
});
export const SearchResult = IDL.Record({
  'listing' : ServiceListing,
  'provider' : Provider,
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'bookingId' : IDL.Nat,
});
export const AvailabilitySlotInput = IDL.Record({
  'status' : SlotStatus,
  'date' : IDL.Text,
  'time' : IDL.Opt(IDL.Text),
});
export const UserInput = IDL.Record({
  'displayName' : IDL.Text,
  'role' : MarketplaceRole,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__bookings' : IDL.Func([], [IDL.Reserved], ['query']),
  '__identities' : IDL.Func([], [IDL.Reserved], ['query']),
  '__listings' : IDL.Func([], [IDL.Reserved], ['query']),
  '__messages' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextBookingId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextListingId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextProviderId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextReviewId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextSlotId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__openAIApiKey' : IDL.Func([], [IDL.Reserved], ['query']),
  '__providers' : IDL.Func([], [IDL.Reserved], ['query']),
  '__reviews' : IDL.Func([], [IDL.Reserved], ['query']),
  '__slots' : IDL.Func([], [IDL.Reserved], ['query']),
  '__users' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'approveProvider' : IDL.Func([IDL.Nat], [Provider], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockAvailabilitySlot' : IDL.Func([IDL.Nat], [AvailabilitySlot], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'checkAvailability' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      ['query'],
    ),
  'completeBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'createBooking' : IDL.Func([BookingInput], [Booking], []),
  'createListing' : IDL.Func([ServiceListingInput], [ServiceListing], []),
  'createReview' : IDL.Func([ReviewInput], [Review], []),
  'declineBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'generateListingDescription' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generatePromotionalContent' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateTitleAndTagline' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceListing)], ['query']),
  'getMyBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getMyDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyIdentity' : IDL.Func([], [IDL.Opt(IdentityAttributes)], ['query']),
  'getMyIdentitySource' : IDL.Func([], [IDL.Opt(IdentitySource)], ['query']),
  'getMyProvider' : IDL.Func([], [IDL.Opt(Provider)], ['query']),
  'getMyUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getProvider' : IDL.Func([IDL.Nat], [IDL.Opt(Provider)], ['query']),
  'getReview' : IDL.Func([IDL.Nat], [IDL.Opt(Review)], ['query']),
  'getThread' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getUnreadMessageCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAvailabilitySlots' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AvailabilitySlot)],
      ['query'],
    ),
  'listListingsByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(ServiceListing)],
      ['query'],
    ),
  'listListingsByProvider' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ServiceListing)],
      ['query'],
    ),
  'listMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listProviderBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'listProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'listProvidersByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Provider)],
      ['query'],
    ),
  'listReviewsByBooking' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'listReviewsByProvider' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'markThreadRead' : IDL.Func([IDL.Nat], [], []),
  'moderateReview' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'hide' : IDL.Null, 'restore' : IDL.Null })],
      [Review],
      [],
    ),
  'registerProvider' : IDL.Func([ProviderInput], [Provider], []),
  'reinstateProvider' : IDL.Func([IDL.Nat], [Provider], []),
  'rejectProvider' : IDL.Func([IDL.Nat, IDL.Text], [Provider], []),
  'respondToReview' : IDL.Func([IDL.Nat, IDL.Text], [Review], []),
  'scheduleBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchProviders' : IDL.Func(
      [SearchFilters],
      [IDL.Vec(SearchResult)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([MessageInput], [Message], []),
  'setAvailabilitySlot' : IDL.Func(
      [AvailabilitySlotInput],
      [AvailabilitySlot],
      [],
    ),
  'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'startBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'suspendProvider' : IDL.Func([IDL.Nat, IDL.Text], [Provider], []),
  'updateListing' : IDL.Func(
      [IDL.Nat, ServiceListingInput],
      [ServiceListing],
      [],
    ),
  'updateMyProvider' : IDL.Func([ProviderInput], [Provider], []),
  'upsertMyUser' : IDL.Func([UserInput], [User], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const BookingStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'reviewed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ServiceCategory = IDL.Variant({
    'boxTruck' : IDL.Null,
    'relocation' : IDL.Null,
    'moving' : IDL.Null,
    'trashHaul' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerNote' : IDL.Opt(IDL.Text),
    'status' : BookingStatus,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Opt(IDL.Text),
    'listingId' : IDL.Nat,
    'createdAt' : Timestamp,
    'jobDetails' : IDL.Text,
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
    'category' : ServiceCategory,
    'customerId' : UserId,
    'providerId' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Provider = IDL.Record({
    'id' : IDL.Nat,
    'ratingSum' : IDL.Nat,
    'verificationNote' : IDL.Opt(IDL.Text),
    'ratingCount' : IDL.Nat,
    'ownerPrincipal' : UserId,
    'logo' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'serviceCategories' : IDL.Vec(ServiceCategory),
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'companyName' : IDL.Text,
    'serviceAreas' : IDL.Vec(IDL.Text),
    'verificationStatus' : VerificationStatus,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SlotStatus = IDL.Variant({
    'blocked' : IDL.Null,
    'available' : IDL.Null,
  });
  const AvailabilitySlot = IDL.Record({
    'id' : IDL.Nat,
    'status' : SlotStatus,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'time' : IDL.Opt(IDL.Text),
    'providerId' : IDL.Nat,
  });
  const BookingInput = IDL.Record({
    'customerNote' : IDL.Opt(IDL.Text),
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Opt(IDL.Text),
    'listingId' : IDL.Nat,
    'jobDetails' : IDL.Text,
    'address' : IDL.Text,
  });
  const ServiceListingInput = IDL.Record({
    'serviceArea' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'priceUnit' : IDL.Text,
    'priceCents' : IDL.Nat,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const ServiceListing = IDL.Record({
    'id' : IDL.Nat,
    'serviceArea' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'category' : ServiceCategory,
    'priceUnit' : IDL.Text,
    'priceCents' : IDL.Nat,
    'providerId' : IDL.Nat,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const ReviewInput = IDL.Record({
    'bookingId' : IDL.Nat,
    'rating' : IDL.Nat,
    'writtenText' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'createdAt' : Timestamp,
    'hidden' : IDL.Bool,
    'updatedAt' : Timestamp,
    'providerResponse' : IDL.Opt(IDL.Text),
    'customerId' : UserId,
    'rating' : IDL.Nat,
    'writtenText' : IDL.Text,
    'providerId' : IDL.Nat,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AuthId = IDL.Principal;
  const IdentitySource = IDL.Variant({
    'internetIdentity' : IDL.Null,
    'google' : IDL.Null,
    'email' : IDL.Null,
  });
  const IdentityAttributes = IDL.Record({
    'principal' : AuthId,
    'lastSeenAt' : IDL.Nat,
    'displayName' : IDL.Opt(IDL.Text),
    'source' : IdentitySource,
    'firstSeenAt' : IDL.Nat,
    'email' : IDL.Opt(IDL.Text),
  });
  const MarketplaceRole = IDL.Variant({
    'admin' : IDL.Null,
    'provider' : IDL.Null,
    'customer' : IDL.Null,
  });
  const User = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : MarketplaceRole,
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'phone' : IDL.Opt(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'bookingId' : IDL.Nat,
    'read' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
  });
  const ProviderInput = IDL.Record({
    'logo' : IDL.Opt(ExternalBlob),
    'serviceCategories' : IDL.Vec(ServiceCategory),
    'description' : IDL.Opt(IDL.Text),
    'companyName' : IDL.Text,
    'serviceAreas' : IDL.Vec(IDL.Text),
  });
  const SearchFilters = IDL.Record({
    'serviceArea' : IDL.Opt(IDL.Text),
    'minRating' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(ServiceCategory),
    'keyword' : IDL.Opt(IDL.Text),
    'maxPriceCents' : IDL.Opt(IDL.Nat),
    'availableOn' : IDL.Opt(IDL.Text),
  });
  const SearchResult = IDL.Record({
    'listing' : ServiceListing,
    'provider' : Provider,
  });
  const MessageInput = IDL.Record({
    'content' : IDL.Text,
    'bookingId' : IDL.Nat,
  });
  const AvailabilitySlotInput = IDL.Record({
    'status' : SlotStatus,
    'date' : IDL.Text,
    'time' : IDL.Opt(IDL.Text),
  });
  const UserInput = IDL.Record({
    'displayName' : IDL.Text,
    'role' : MarketplaceRole,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__bookings' : IDL.Func([], [IDL.Reserved], ['query']),
    '__identities' : IDL.Func([], [IDL.Reserved], ['query']),
    '__listings' : IDL.Func([], [IDL.Reserved], ['query']),
    '__messages' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextBookingId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextListingId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextProviderId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextReviewId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextSlotId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__openAIApiKey' : IDL.Func([], [IDL.Reserved], ['query']),
    '__providers' : IDL.Func([], [IDL.Reserved], ['query']),
    '__reviews' : IDL.Func([], [IDL.Reserved], ['query']),
    '__slots' : IDL.Func([], [IDL.Reserved], ['query']),
    '__users' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'approveProvider' : IDL.Func([IDL.Nat], [Provider], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockAvailabilitySlot' : IDL.Func([IDL.Nat], [AvailabilitySlot], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'checkAvailability' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        ['query'],
      ),
    'completeBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'createBooking' : IDL.Func([BookingInput], [Booking], []),
    'createListing' : IDL.Func([ServiceListingInput], [ServiceListing], []),
    'createReview' : IDL.Func([ReviewInput], [Review], []),
    'declineBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'generateListingDescription' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generatePromotionalContent' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateTitleAndTagline' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceListing)], ['query']),
    'getMyBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getMyDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyIdentity' : IDL.Func([], [IDL.Opt(IdentityAttributes)], ['query']),
    'getMyIdentitySource' : IDL.Func([], [IDL.Opt(IdentitySource)], ['query']),
    'getMyProvider' : IDL.Func([], [IDL.Opt(Provider)], ['query']),
    'getMyUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getProvider' : IDL.Func([IDL.Nat], [IDL.Opt(Provider)], ['query']),
    'getReview' : IDL.Func([IDL.Nat], [IDL.Opt(Review)], ['query']),
    'getThread' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getUnreadMessageCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAvailabilitySlots' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AvailabilitySlot)],
        ['query'],
      ),
    'listListingsByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(ServiceListing)],
        ['query'],
      ),
    'listListingsByProvider' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ServiceListing)],
        ['query'],
      ),
    'listMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listProviderBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'listProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'listProvidersByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Provider)],
        ['query'],
      ),
    'listReviewsByBooking' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'listReviewsByProvider' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'markThreadRead' : IDL.Func([IDL.Nat], [], []),
    'moderateReview' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'hide' : IDL.Null, 'restore' : IDL.Null })],
        [Review],
        [],
      ),
    'registerProvider' : IDL.Func([ProviderInput], [Provider], []),
    'reinstateProvider' : IDL.Func([IDL.Nat], [Provider], []),
    'rejectProvider' : IDL.Func([IDL.Nat, IDL.Text], [Provider], []),
    'respondToReview' : IDL.Func([IDL.Nat, IDL.Text], [Review], []),
    'scheduleBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchProviders' : IDL.Func(
        [SearchFilters],
        [IDL.Vec(SearchResult)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([MessageInput], [Message], []),
    'setAvailabilitySlot' : IDL.Func(
        [AvailabilitySlotInput],
        [AvailabilitySlot],
        [],
      ),
    'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'startBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'suspendProvider' : IDL.Func([IDL.Nat, IDL.Text], [Provider], []),
    'updateListing' : IDL.Func(
        [IDL.Nat, ServiceListingInput],
        [ServiceListing],
        [],
      ),
    'updateMyProvider' : IDL.Func([ProviderInput], [Provider], []),
    'upsertMyUser' : IDL.Func([UserInput], [User], []),
  });
};

export const init = ({ IDL }) => { return []; };